[development]
address = "localhost"
port = 8000
workers = [16]
log = "normal"
secret_key = "82a+5sGT+TjflswbYuHJr27CzVkfCFWYZ1AlKnhASu8="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
workers = [16]
log = "normal"
secret_key = "6aqTS7DVAp5hKyyPSDcmsCdzMx1+x7Udg9BUmTd/IL4="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
workers = [16]
log = "critical"
secret_key = "afk/fCfTdK4GXAO+y50eQt+SiyYvHFZGpyTDXW5rrQ8="
limits = { forms = 32768 }